stages:
  - install
  - test
  - publish

cache:
  paths:
    - vendor/
    - test/vendor/

install:
  image: containerhub.ncsa.tech:5000/composer:2
  stage: install
  except:
    - tags
  script:
    - composer require
    - composer --working-dir=test/ require

test:
  image: containerhub.ncsa.tech:5000/php:8.0-cli-alpine
  stage: test
  except:
    - tags
  artifacts:
    reports:
      junit: phpunit-report.xml
  script:
    - /bin/sh test/scripts/run-tests.sh

# Only used in php-mcj-release
publish:
  image: curlimages/curl:latest
  stage: publish
  only:
  - tags
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - echo $URL
    - response=$(curl -s -w "\n%{http_code}" $insecure --data tag=${CI_COMMIT_TAG} $URL)
    - echo $response
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
        echo "Package created - Code $code - $body";
      else
        echo "Could not create package - Code $code - $body";
        exit 1;
      fi
