services:
    php:
        image: php:8.0-cli-alpine
        working_dir: /usr/src/myapp
        command: ["sh", "scripts/start-dev-server.sh"]
        ports:
            - "8081:8081"
        volumes:
            - .:/usr/src/myapp