<?php namespace net\peacefulcraft\apirouter\spec\cli;

/**
 * Terminal formatting codes
 */
interface Format {

	CONST COLOR_BLACK = '0;30';
	CONST COLOR_GREY = '1;30';
	CONST COLOR_LIGHT_GREY = '0;37';

	CONST COLOR_RED = '0;31';
	CONST COLOR_LIGHT_RED = '1;31';

	CONST COLOR_GREEN = '0;32';
	CONST COLOR_LIGHT_GREEN = '1;30';

	CONST COLOR_BROWN = '0;33';
	CONST COLOR_YELLOW = '1;33';

	CONST COLOR_BLUE = '0;34';
	CONST COLOR_LIGHT_BLUE = '1;34';

	CONST COLOR_PURPLE = '0;35';
	CONST COLOR_LIGHT_PURPLE = '1;35';

	CONST COLOR_CYAN = '0;36';
	CONST COLOR_LIGHT_CYAN = '1;36';

	CONST COLOR_WHITE = '1;37';
	CONST COLOR_RESET = '0;39';

	CONST BG_BLACK = '40';
	CONST BG_RED = '41';
	CONST BG_GREEN = '42';
	CONST BG_YELLOW = '43';
	CONST BG_BLUE = '44';
	CONST BG_MAGENTA = '45';
	CONST BG_CYAN = '46';
	CONST BG_LIGHT_GREY = '47';

	CONST TEXT_UNDERLINE = '4';
	CONST TEXT_BLINK = '5';
	CONST TEXT_REVERSE = '7';
	CONST TEXT_HIDDEN = '8';
}

?>